### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by gevraud** [CyberCX-STA/PurpleOps#33]
Hello,

Is it possible to run this application on Kubernetes ? If yes, could you provide an example ?

I tried but I always got some python stacktraces like this one : 

```
[2024-12-05 10:01:46 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-12-05 10:01:46 +0000] [1] [INFO] Using worker: sync
[2024-12-05 10:01:46 +0000] [7] [INFO] Booting worker with pid: 7
[2024-12-05 10:01:46 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'purpleops'
[2024-12-05 10:01:46 +0000] [7] [INFO] Worker exiting (pid: 7)
[2024-12-05 10:01:46 +0000] [1] [INFO] Shutting down: Master
[2024-12-05 10:01:46 +0000] [1] [INFO] Reason: Worker failed to boot.
```

Regards

**Comment by sidhu2003** [comment]
hey @gevraud, I have experience deploying python applications with kubernetes, please assign me this issue so that I can work on it. You can check my profile for my previous work, Thank you.
